import 'server-only';
import sanitizeHtml from 'sanitize-html';

// Diagrams are author-supplied SVG rendered inline. Keep drawing elements and geometry only:
// no scripts, event handlers, links, external images, foreign HTML or inline styles.

const ELEMENTS = [
  'svg',
  'g',
  'defs',
  'title',
  'desc',
  'path',
  'rect',
  'circle',
  'ellipse',
  'line',
  'polyline',
  'polygon',
  'text',
  'tspan',
  'marker',
  'linearGradient',
  'radialGradient',
  'stop',
  'pattern',
  'clipPath',
  'mask',
];

const ATTRIBUTES = [
  'id',
  'class',
  'viewBox',
  'width',
  'height',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'd',
  'points',
  'transform',
  'fill',
  'fill-opacity',
  'fill-rule',
  'stroke',
  'stroke-width',
  'stroke-opacity',
  'stroke-dasharray',
  'stroke-linecap',
  'stroke-linejoin',
  'opacity',
  'font-family',
  'font-size',
  'font-weight',
  'text-anchor',
  'dominant-baseline',
  'dx',
  'dy',
  'markerWidth',
  'markerHeight',
  'refX',
  'refY',
  'orient',
  'marker-start',
  'marker-mid',
  'marker-end',
  'offset',
  'stop-color',
  'stop-opacity',
  'gradientUnits',
  'patternUnits',
  'clip-path',
  'mask',
  'preserveAspectRatio',
  'xmlns',
  'role',
  'aria-label',
];

/** Allow-listed SVG markup, safe to render inline. */
export function sanitizeSvg(svg: string): string {
  return sanitizeHtml(svg, {
    allowedTags: ELEMENTS,
    allowedAttributes: { '*': ATTRIBUTES },
    allowedSchemes: [],
    parser: { lowerCaseTags: false, lowerCaseAttributeNames: false },
  });
}
